# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Twitter sentiment search
email: TK
description: > # this means to ignore newlines until "baseurl:"
  Analyze Twitter sentiment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://TK" # the base hostname & protocol for your site
twitter_username: TK
github_username:  TK

# Build settings
markdown: kramdown
source: src
destination: public
